Quizz\QuizzBundle\Entity\Admins:
    type: entity
    table: Admins
    id:
        id_admin:
            type: integer
            generator: { strategy: AUTO }
    fields:
        login_admin:
            type: string
            length: 45
        name_admin:
            type: string
            lenght: 45
        surname_admin:
            type: string
            length: 45
        mail_admin:
            type: string
            length: 50
        pwd_admin:
            type: string
            length: 32
        key_admin:
            type: string
            length: 32