Quizz\QuizzBundle\Entity\Classroom:
    type: entity
    table: classroom
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 20
    oneToMany:
            array_users:
                targetEntity: Users
                mappedBy: fk_idclass
    manyToMany:
            classrooms_array:
              targetEntity: Themes
              mappedBy: themes_array