Quizz\QuizzBundle\Entity\Classroom:
    type: entity
    table: classroom
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 20
    oneToMany:
            array_users:
                targetEntity: Users
                mappedBy: fk_idclass
    manyToMany:
        themes_array:
          targetEntity: Themes
          inversedBy: classrooms_array
          joinTable:
            name: classroom_has_theme
            joinColumns:
              id_classroom:
                referencedColumnName: id
            inverseJoinColumns:
              id_theme:
                referencedColumnName: id