Quizz\QuizzBundle\Entity\Classroom:
    type: entity
    table: Classroom
    id:
        id_classroom:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name_classroom:
            type: string
            length: 20
        key_classroom:
            type: string
            lenght: 32
        fk_id_teacher:
            type: integer