Quizz\QuizzBundle\Entity\Levels:
    type: entity
    table: levels
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180
        description:
            type: string
            lenght: 320
    manyToOne:
            fk_idtheme:
                targetEntity: Themes
                inversedBy: array_levels
                joinColumn:
                    name: idtheme
                    referencedColumnName: id
    oneToMany:
            array_quizz:
                targetEntity: Quizz
                mappedBy: fk_idlevel