Quizz\QuizzBundle\Entity\Messages:
    type: entity
    table: Messages
    id:
        id_message:
            type: integer
            generator: { strategy: AUTO }
    fields:
        content_message:
            type: text
        subject_message:
            type: string
            lenght: 180
        key_sender:
            type: string
            length: 32
        key_receiver:
            type: string
            length: 32