Quizz\QuizzBundle\Entity\Questions:
    type: entity
    table: questions
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        enunciated:
            type: string
            length: 320
        style:
            type: string
            length: 20

    manyToOne:
            Quizz:
                targetEntity: Quizz
                inversedBy: id
                joinColumn:
                    name: idquizz
                    referencedColumnName: id
    oneToOne:
        idanswer:
          targetEntity: Answers
          joinColumn:
            name: idanswer
            referencedColumnName: id