Quizz\QuizzBundle\Entity\QuizzAnswer:
    type: entity
    table: QuizzAnswer
    id:
        id_answer:
            type: integer
            generator: { strategy: AUTO }
    fields:
        fk_id_quizz_question:
            type: integer
        fk_id_quizz:
            type: integer
        type_answer:
            type: string
            length: 45
        level_quizz:
            type: integer
            length: 10
        answer_value:
            type: text