Quizz\QuizzBundle\Entity\QuizzQuestion:
    type: entity
    table: QuizzQuestion
    id:
        id_question_quizz:
            type: integer
            generator: { strategy: AUTO }
    fields:
        key_quizz:
            type: string
            length: 32
        type_question:
            type: string
            length: 45
        fk_id_answer:
            type: integer
        fk_id_quizz:
            type: integer