Quizz\QuizzBundle\Entity\Quizz:
    type: entity
    table: quizz
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 180
        description:
            type: string
            length: 320
        level:
            type: integer
            length: 10
    manyToOne:
            fk_idlevel:
                targetEntity: Levels
                inversedBy: array_quizz
                joinColumn:
                    name: idtheme
                    referencedColumnName: id
    oneToMany:
        fk_questions:
            targetEntity: Questions
            mappedBy: fk_quizz