Quizz\QuizzBundle\Entity\StudentsLogs:
    type: entity
    table: StudentsLogs
    id:
        id_log:
            type: integer
            generator: { strategy: AUTO }
    fields:
        time_log:
            type: datetime
        successed_quizz:
            type: boolean
        failed_quizz:
            type: boolean
        fk_id_eleve:
            type: integer