Quizz\QuizzBundle\Entity\Students:
    type: entity
    table: Students
    id:
        id_student:
            type: integer
            generator: { strategy: AUTO }
    fields:
        login_student:
            type: string
            length: 45
        name_student:
            type: string
            lenght: 45
        surname_student:
            type: string
            length: 45
        mail_student:
            type: string
            length: 50
        pwd_student:
            type: string
            length: 32
        key_student:
            type: string
            length: 32
        fk_id_classroom:
            type: integer