Quizz\QuizzBundle\Entity\Themes:
    type: entity
    table: themes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180
    oneToMany:
            classHasQuizz:
                targetEntity: classHasQuizz
                mappedBy: idtheme
    oneToMany:
            Quizz:
                targetEntity: Quizz
                mappedBy: id