Quizz\QuizzBundle\Entity\Themes:
    type: entity
    table: themes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180
            unique: true
        description:
            type: string
            lenght: 320
    oneToMany:
            array_theme:
                targetEntity: Levels
                mappedBy: fk_idtheme