Quizz\QuizzBundle\Entity\Themes:
    type: entity
    table: themes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180
        description:
            type: string
            lenght: 320
    oneToMany:
            array_quizz:
                targetEntity: Quizz
                mappedBy: fk_idtheme
    manyToMany:
        groups:
            targetEntity: Classroom
            inversedBy: classrooms
            joinTable:
                name: classHasTheme
                joinColumns:
                  theme_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  classroom_id:
                    referencedColumnName: id