Quizz\QuizzBundle\Entity\Themes:
    type: entity
    table: themes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180
            unique: true
        description:
            type: string
            lenght: 320
    oneToMany:
            array_theme:
                targetEntity: Levels
                mappedBy: fk_idtheme
    manyToOne:
            fk_autorid:
                targetEntity: Users
                inversedBy: array_autors
                joinColumn:
                    name: idautors
                    referencedColumnName: id
    oneToMany:
            array_levels:
                targetEntity: Quizz
                mappedBy: fk_idlevel
    manyToMany:
            themes_array:
              targetEntity: Classroom
              inversedBy: classrooms_array
              joinTable:
                name: classroom_has_theme
                joinColumns:
                  id_classroom:
                    referencedColumnName: id
                inverseJoinColumns:
                  id_theme:
                    referencedColumnName: id