Quizz\QuizzBundle\Entity\Themes:
    type: entity
    table: themes
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180
        description:
            type: string
            lenght: 320
    oneToMany:
            array_theme:
                targetEntity: classHasQuizz
                mappedBy: fk_idtheme
            array_quizz:
                targetEntity: Quizz
                mappedBy: fk_idtheme