Quizz\QuizzBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 25
            unique: true
        password:
            type: string
            length: 100
        email:
            type: string
            length: 60
            unique: true
        isActive:
            type: boolean
        roles:
            type: string
            length: 20
        name:
            type: string
            length: 20
        lastname:
            type: string
            length: 20
    manyToOne:
        idclass:
            targetEntity: Classroom
            inversedBy: id
            joinColumn:
                name: idclass
                referencedColumnName: id